### ISSUE TITLE
Choice 'st7789v' for option 'lcd_type' in section 'display' is not a valid choice

### ISSUE THREAD

**Issue by willuk2010** [matthewlloyd/klipper#4]
Hey @matthewlloyd !

Managed to flash my prusa mini, and connect it to Klipper all good!

But the display on the mini says "Developer Firmware", and if i leave the [display] section in the printer.cfg i get

"Choice 'st7789v' for option 'lcd_type' in section 'display' is not a valid choice"

If i remove it, it connects fine.

Many thanks!

**Comment by matthewlloyd** [comment]
Check that you have the prusamini branch checked out, and that in the file klipper/klippy/extras/display/display.py you have st7789v listed under LCD_types.

**Comment by willuk2010** [comment]
defo on your branch mate,

* prusamini
lines 1-1/1 (END)

and, contents of that file looks right.

LCD_chips = {
    'st7920': st7920.ST7920, 'emulated_st7920': st7920.EmulatedST7920,
    'hd44780': hd44780.HD44780, 'uc1701': uc1701.UC1701,
    'ssd1306': uc1701.SSD1306, 'sh1106': uc1701.SH1106,
    'hd44780_spi': hd44780_spi.hd44780_spi,
    'st7789v': st7789v.ST7789V
}

**Comment by matthewlloyd** [comment]
Can you share your /tmp/klippy.log file?

**Comment by willuk2010** [comment]
Sure, here you!

[klipper.log](https://github.com/matthewlloyd/klipper/files/7112031/klipper.log)

**Comment by matthewlloyd** [comment]
Must be something else going on. If you look at the error:

```
Config error
Traceback (most recent call last):
  File "/home/klippy/klipper/klippy/klippy.py", line 157, in _connect
    self._read_config()
  File "/home/klippy/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/klippy/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/klippy/klipper/klippy/extras/display/__init__.py", line 9, in load_config
    return display.load_config(config)
  File "/home/klippy/klipper/klippy/extras/display/display.py", line 248, in load_config
    return PrinterLCD(config)
  File "/home/klippy/klipper/klippy/extras/display/display.py", line 91, in __init__
    self.lcd_chip = config.getchoice('lcd_type', LCD_chips)(config)
  File "/home/klippy/klipper/klippy/configfile.py", line 75, in getchoice
    " is not a valid choice" % (c, option, self.section))
Error: Choice 'st7789v' for option 'lcd_type' in section 'display' is not a valid choice
```

You can see that it's impossible for this assert to fail if 'st7789v' is really in LCD_chips. So you must not be running against the code that you looked at earlier. Do you have multiple Klipper / Klippy checkouts or something?

**Comment by willuk2010** [comment]
Think i have figured it out, i have over complicated things :)

Im using klipper in a docker on a server, not on a rpi... i suspect this could be the issue,

firmware is flashed with your "prusamini" branch, but the running clipper is from somewhere else! 

I should update the docker with your klipper, and try again.

Sorry for the confusion, but you did help :)

**Comment by matthewlloyd** [comment]
No worries, glad you figured it out.
